# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb2bb18a56bccbf06d493054436e1b58f0e4ab6a47865a5fd52c12c94d2a17bb98e25b8157d54017ad96d8ed16056241df0f9be7b0a8065355cbc9e355578723

test:
  secret_key_base: 0c7b606897a0e75881c4e2bfd4001b78f8f7006c5bb89506df58d76111f1fde51a8872f839dcc82e08bbcae056fe069d2b149412953c6b3bb36fa5fe6ee18355

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
